003 view role capability
Jadevious/kainos-recruitment-ui pull request #10
Opened 2022-10-04 11:13 UTC by conormcgee480

Ticket: https://trello.com/c/QQ8bnJ3o

Added capability field to job roles page table and extra capability field in the unit tests

2022-10-06 09:27 UTC, Kirsten1822 requested changes
There's still some weird white spacing in JobRolesTests.js if someone could take a look in the file please

2022-10-06 10:00 UTC, Kirsten1822 approved these changes

2022-10-06 10:03 UTC, boydstepnew approved these changes

2022-10-07 11:15 UTC, boydstepnew commented on test/JobRolesAutomationTest.js
> +        await driver.get(baseUrl + '/job-roles')
'/job-roles' is getting repeated now, let's add it as a variable :)

2022-10-07 11:18 UTC, boydstepnew approved these changes

2022-10-07 14:10 UTC, merged