004 view role band level
Jadevious/kainos-recruitment-ui pull request #11
Opened 2022-10-04 14:51 UTC by Kirsten1822

Ticket Link for US004: https://trello.com/c/GJSWrpFy

2022-10-04 15:06 UTC, Jadevious commented on .gitignore
> +**/DS_Store
Outdated, fixed in changes to 001

2022-10-06 09:24 UTC, Jadevious requested changes

2022-10-06 09:24 UTC, Jadevious commented on data/jobdata.js
> +
Unnecessary white space on line 3

2022-10-06 09:24 UTC, Jadevious commented on views/jobs.html
> -
We need to keep the ID system in to allow QA/Selenium testing

2022-10-06 10:03 UTC, boydstepnew approved these changes

2022-10-06 11:04 UTC, Jadevious approved these changes

2022-10-10 14:50 UTC, merged