Create main.yml
Jadevious/kainos-recruitment-ui pull request #2
Opened 2022-09-27 14:31 UTC by Jadevious

2022-09-27 14:32 UTC, Jadevious commented
Link to ticket: https://trello.com/c/2Y6hQ5Ul

2022-09-27 14:33 UTC, Kirsten1822 approved these changes

2022-09-27 15:44 UTC, JoshKainos commented on .github/workflows/main.yml
> +        run: npm install
You are missing these lines

- run: npm run build --if-present 
- run: npm test

Test can be omitted for now as there are no tests but a tech debt ticket will be required to include later

2022-09-28 07:54 UTC, JoshKainos requested changes

2022-09-28 07:54 UTC, JoshKainos commented on .github/workflows/main.yml
> +        run: |
```suggestion
    - run: npm install
```

2022-09-28 07:54 UTC, JoshKainos commented on .github/workflows/main.yml
> +          npm install
```suggestion
        - run: npm run build --if-present
```

2022-09-28 07:54 UTC, JoshKainos commented on .github/workflows/main.yml
> +          run: npm run build --if-present
Remove this line

2022-09-28 08:19 UTC, JoshKainos approved these changes

2022-09-28 08:27 UTC, merged